/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkCreate
 */
export interface WorkCreate {
    /**
     * 
     * @type {string}
     * @memberof WorkCreate
     */
    item: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkCreate
     */
    startDatetime: Date;
    /**
     * 
     * @type {boolean}
     * @memberof WorkCreate
     */
    isActive: boolean;
}

export function WorkCreateFromJSON(json: any): WorkCreate {
    return WorkCreateFromJSONTyped(json, false);
}

export function WorkCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item': json['item'],
        'startDatetime': (new Date(json['start_datetime'])),
        'isActive': json['is_active'],
    };
}

export function WorkCreateToJSON(value?: WorkCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item': value.item,
        'start_datetime': (value.startDatetime.toISOString()),
        'is_active': value.isActive,
    };
}

