/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkUpdate
 */
export interface WorkUpdate {
    /**
     * 
     * @type {string}
     * @memberof WorkUpdate
     */
    item: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkUpdate
     */
    startDatetime: Date;
    /**
     * 
     * @type {boolean}
     * @memberof WorkUpdate
     */
    isActive: boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkUpdate
     */
    memo?: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkUpdate
     */
    endDatetime?: Date;
    /**
     * 
     * @type {number}
     * @memberof WorkUpdate
     */
    duration?: number;
}

export function WorkUpdateFromJSON(json: any): WorkUpdate {
    return WorkUpdateFromJSONTyped(json, false);
}

export function WorkUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item': json['item'],
        'startDatetime': (new Date(json['start_datetime'])),
        'isActive': json['is_active'],
        'memo': !exists(json, 'memo') ? undefined : json['memo'],
        'endDatetime': !exists(json, 'end_datetime') ? undefined : (new Date(json['end_datetime'])),
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
    };
}

export function WorkUpdateToJSON(value?: WorkUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item': value.item,
        'start_datetime': (value.startDatetime.toISOString()),
        'is_active': value.isActive,
        'memo': value.memo,
        'end_datetime': value.endDatetime === undefined ? undefined : (value.endDatetime.toISOString()),
        'duration': value.duration,
    };
}

